/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientmansys;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author saad_
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form window
     */
    public Window() throws SQLException {
        initComponents();
        
        this.setResizable(false);
        lForm = new LoginForm(this);
//        btnControlCenter.setVisible(false);
//        btnLogout.setVisible(false);
//        btnLogin.setVisible(true);
//        
        desktopPane.setBackground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnControlCenter = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        titleName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        btnControlCenter.setText("Control Center");
        btnControlCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlCenterActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Management System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                desktopPaneComponentResized(evt);
            }
        });

        titleName.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Pateint Management System | Login");
        desktopPane.add(titleName);
        titleName.setBounds(0, 210, 700, 40);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        desktopPane.add(txtName);
        txtName.setBounds(190, 280, 430, 50);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        desktopPane.add(txtPass);
        txtPass.setBounds(190, 340, 430, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Employee ID");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(50, 280, 110, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(50, 340, 110, 50);

        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        desktopPane.add(btnLogin1);
        btnLogin1.setBounds(190, 400, 290, 60);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        desktopPane.add(btnCancel);
        btnCancel.setBounds(480, 400, 140, 60);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        desktopPane.add(jSeparator1);
        jSeparator1.setBounds(350, 40, 10, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientmansys/img/logo-hospital-png-1.png"))); // NOI18N
        desktopPane.add(jLabel3);
        jLabel3.setBounds(120, 20, 130, 156);

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 32)); // NOI18N
        jLabel4.setText("Hospital");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(440, 90, 141, 40);

        jLabel5.setFont(new java.awt.Font("Montserrat Black", 0, 36)); // NOI18N
        jLabel5.setText("Halflife");
        desktopPane.add(jLabel5);
        jLabel5.setBounds(440, 60, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Session.setLoggedIn(false);
        updateScreen();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void desktopPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_desktopPaneComponentResized
        updateScreen();
    }//GEN-LAST:event_desktopPaneComponentResized

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        lForm.setTxtName("");
        lForm.setTxtPass("");
        lForm.setVisible(true);
        desktopPane.add(lForm);
        desktopPane.setComponentZOrder(lForm, 1);
        updateScreen();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnControlCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlCenterActionPerformed
        commandCenter.setVisible(true);
        commandCenter.setGreeting(Session.getName());
        desktopPane.add(commandCenter);
        desktopPane.setComponentZOrder(commandCenter, 0);
        updateScreen();
    }//GEN-LAST:event_btnControlCenterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed

    }//GEN-LAST:event_txtPassActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        Validate v = new Validate();
        try {
            user = v.validateSignup(txtName.getText(), txtPass.getPassword());
            if (user != null) {
                this.dispose();
                Session.setId(Integer.parseInt(txtName.getText()));
                Session.setName(user.getName());
                Session.setLoggedIn(true);
                commandCenter = new CommandWindow(user);
                commandCenter.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Login Successful!");
                updateScreen();
            }
        } catch (UserValidationException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    void updateScreen() {
        
//        final int h = desktopPane.getHeight();
//        final int w = desktopPane.getWidth();
//        int divW = w / 4, divH = h / 12;
//        
//        if (Session.isLoggedIn()) {
//            btnControlCenter.setBounds(divW, divH * 4, divW * 2, divH * 2);
//            btnLogout.setBounds(divW, divH * 8, divW * 2, divH * 2);
//            
//            if (btnLogin.isVisible()) {
//                btnControlCenter.setVisible(true);
//                btnLogout.setVisible(true);
//                btnLogin.setVisible(false);
//            } 
//        } else {
//            btnLogin.setBounds(divW, divH * 5, divW * 2, divH * 2);
//            
//            if(!btnLogin.isVisible()) {
//                btnControlCenter.setVisible(false);
//                btnLogout.setVisible(false);
//                btnLogin.setVisible(true);
//            }
//        }
//        titleName.setBounds(0, divH / 2, w, divH * 2);
        desktopPane.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Window().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void addNewWindow(JInternalFrame patientAddWindow) {
        patientAddWindow.setVisible(true);
        desktopPane.add(patientAddWindow);
        desktopPane.setComponentZOrder(patientAddWindow, 0);
        updateScreen();
    }
    public void addNewWindow(JFrame patientAddWindow) {
        patientAddWindow.setVisible(true);
        desktopPane.add(patientAddWindow);
        desktopPane.setComponentZOrder(patientAddWindow, 0);
        updateScreen();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnControlCenter;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titleName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
    private LoginForm lForm;
    private CommandWindow commandCenter;
    private Staff user;
}
